services:
  - type: web
    name: adipay-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRY
        value: 7d
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false